### ISSUE TITLE
Users can see a introduction page to the app with links to main sections

### ISSUE THREAD

**Issue by nik0lz** [fac-13/SBSHS#2]
- [x] Users can see a intro message on landing page #3 
- [x] When the "stories" button is clicked, users can see all available case studies #6 
- [x] When the "theory" button is clicked, users can see links to more material #5
